# Anuswara and related
MAL_ANUSWARA_ABV = "\u0D00"
MAL_CHANDRABINDU = "\u0D01"
MAL_ANUSWARA = "\u0D02"
MAL_VISAGRA = "\u0D03"


# Swaraksharam
MAL_SWARAKSHARAM_A = "\u0D05"
MAL_SWARAKSHARAM_AA = "\u0D06"
MAL_SWARAKSHARAM_I = "\u0D07"
MAL_SWARAKSHARAM_II = "\u0D08"
MAL_SWARAKSHARAM_U = "\u0D09"
MAL_SWARAKSHARAM_UU = "\u0D0A"
MAL_SWARAKSHARAM_ERU = "\u0D0B"
MAL_SWARAKSHARAM_E = "\u0D0E"
MAL_SWARAKSHARAM_EE = "\u0D0F"
MAL_SWARAKSHARAM_AI = "\u0D10"
MAL_SWARAKSHARAM_O = "\u0D12"
MAL_SWARAKSHARAM_OO = "\u0D13"
MAL_SWARAKSHARAM_OU = "\u0D14"


# Vyanjanaksharam
MAL_VYANJANAKSHARAM_KA = "\u0D15"
MAL_VYANJANAKSHARAM_KHA = "\u0D16"
MAL_VYANJANAKSHARAM_GA = "\u0D17"
MAL_VYANJANAKSHARAM_GHA = "\u0D18"
MAL_VYANJANAKSHARAM_NGA = "\u0D19"
MAL_VYANJANAKSHARAM_CA = "\u0D1A"
MAL_VYANJANAKSHARAM_CHA = "\u0D1B"
MAL_VYANJANAKSHARAM_JA = "\u0D1C"
MAL_VYANJANAKSHARAM_JHA = "\u0D1D"
MAL_VYANJANAKSHARAM_NJA = "\u0D1E"
MAL_VYANJANAKSHARAM_TTA = "\u0D1F"
MAL_VYANJANAKSHARAM_TTHA = "\u0D20"
MAL_VYANJANAKSHARAM_DDA = "\u0D21"
MAL_VYANJANAKSHARAM_DDHA = "\u0D22"
MAL_VYANJANAKSHARAM_NNA = "\u0D23"
MAL_VYANJANAKSHARAM_TA = "\u0D24"
MAL_VYANJANAKSHARAM_THA = "\u0D25"
MAL_VYANJANAKSHARAM_DA = "\u0D26"
MAL_VYANJANAKSHARAM_DHA = "\u0D27"
MAL_VYANJANAKSHARAM_NA = "\u0D28"
MAL_VYANJANAKSHARAM_PA = "\u0D2A"
MAL_VYANJANAKSHARAM_PHA = "\u0D2B"
MAL_VYANJANAKSHARAM_BA = "\u0D2C"
MAL_VYANJANAKSHARAM_BHA = "\u0D2D"
MAL_VYANJANAKSHARAM_MA = "\u0D2E"
MAL_VYANJANAKSHARAM_YA = "\u0D2F"
MAL_VYANJANAKSHARAM_RA = "\u0D30"
MAL_VYANJANAKSHARAM_RRA = "\u0D31"
MAL_VYANJANAKSHARAM_LA = "\u0D32"
MAL_VYANJANAKSHARAM_LLA = "\u0D33"
MAL_VYANJANAKSHARAM_ZHA = "\u0D34"
MAL_VYANJANAKSHARAM_VA = "\u0D35"
MAL_VYANJANAKSHARAM_SHA = "\u0D36"
MAL_VYANJANAKSHARAM_SSA = "\u0D37"
MAL_VYANJANAKSHARAM_SA = "\u0D38"
MAL_VYANJANAKSHARAM_HA = "\u0D39"


# Chillaksharam
MAL_CHILLAKSHARAM_NN = "\u0D7A"
MAL_CHILLAKSHARAM_N = "\u0D7B"
MAL_CHILLAKSHARAM_RR = "\u0D7C"
MAL_CHILLAKSHARAM_L = "\u0D7D"
MAL_CHILLAKSHARAM_LL = "\u0D7E"


# Half Vowels
MAL_VOWEL_AA = "\u0D3E"
MAL_VOWEL_I = "\u0D3F"
MAL_VOWEL_II = "\u0D40"
MAL_VOWEL_U = "\u0D41"
MAL_VOWEL_UU = "\u0D42"
MAL_VOWEL_R = "\u0D43"
MAL_VOWEL_E = "\u0D46"
MAL_VOWEL_EE = "\u0D47"
MAL_VOWEL_AI = "\u0D48"
MAL_VOWEL_O = "\u0D4A"
MAL_VOWEL_OO = "\u0D4B"
MAL_VOWEL_OU = "\u0D57"
MAL_VOWEL_VIRAMAM = "\u0D4D"  # CHANDRAKKALA
MAL_VOWEL_DOT = "\u0D4E"


# Half Consonants
MAL_HALF_CONSONANT_YA = MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_YA
MAL_HALF_CONSONANT_RA = MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA
MAL_HALF_CONSONANT_VA = MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_VA


# KOOTTAKSHARAM
MAL_KOOTTAKSHARAM_KKA = MAL_VYANJANAKSHARAM_KA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_KA
MAL_KOOTTAKSHARAM_KSSA = MAL_VYANJANAKSHARAM_KA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_SSA
MAL_KOOTTAKSHARAM_KLLA = MAL_VYANJANAKSHARAM_KA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_KTA = MAL_VYANJANAKSHARAM_KA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_TA
MAL_KOOTTAKSHARAM_KRA = MAL_VYANJANAKSHARAM_KA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_GGA = MAL_VYANJANAKSHARAM_GA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_GA
MAL_KOOTTAKSHARAM_GLLA = MAL_VYANJANAKSHARAM_GA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_GRA = MAL_VYANJANAKSHARAM_GA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA
MAL_KOOTTAKSHARAM_GNA = MAL_VYANJANAKSHARAM_GA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NA
MAL_KOOTTAKSHARAM_GDA = MAL_VYANJANAKSHARAM_GA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DA
MAL_KOOTTAKSHARAM_GMA = MAL_VYANJANAKSHARAM_GA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_MA

MAL_KOOTTAKSHARAM_NGKA = MAL_VYANJANAKSHARAM_NGA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_KA
MAL_KOOTTAKSHARAM_NGNGA = MAL_VYANJANAKSHARAM_NGA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NGA

MAL_KOOTTAKSHARAM_CCA = MAL_VYANJANAKSHARAM_CA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_CA
MAL_KOOTTAKSHARAM_CCHA = MAL_VYANJANAKSHARAM_CA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_CHA

MAL_KOOTTAKSHARAM_JJA = MAL_VYANJANAKSHARAM_JA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_JA
MAL_KOOTTAKSHARAM_JNJA = MAL_VYANJANAKSHARAM_JA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NJA

MAL_KOOTTAKSHARAM_NJNJA = MAL_VYANJANAKSHARAM_NJA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NJA
MAL_KOOTTAKSHARAM_NJCA = MAL_VYANJANAKSHARAM_NJA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_CA

MAL_KOOTTAKSHARAM_TTTTA = MAL_VYANJANAKSHARAM_TTA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_TTA
MAL_KOOTTAKSHARAM_TTRA = MAL_VYANJANAKSHARAM_TTA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_DDDDA = MAL_VYANJANAKSHARAM_DDA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DDA
MAL_KOOTTAKSHARAM_DDDDHA = MAL_VYANJANAKSHARAM_DDA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DDHA

MAL_KOOTTAKSHARAM_NNNNA = MAL_VYANJANAKSHARAM_NNA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NNA
MAL_KOOTTAKSHARAM_NNTTA = MAL_VYANJANAKSHARAM_NNA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_TTA
MAL_KOOTTAKSHARAM_NNDDA = MAL_VYANJANAKSHARAM_NNA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DDA
MAL_KOOTTAKSHARAM_NNDDHA = MAL_VYANJANAKSHARAM_NNA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DDHA
MAL_KOOTTAKSHARAM_NNMA = MAL_VYANJANAKSHARAM_NNA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_MA

MAL_KOOTTAKSHARAM_TTA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_TA
MAL_KOOTTAKSHARAM_TTHA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_THA
MAL_KOOTTAKSHARAM_TNA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NA
MAL_KOOTTAKSHARAM_TMA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_MA
MAL_KOOTTAKSHARAM_TBHA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_BHA
MAL_KOOTTAKSHARAM_TSA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_SA
MAL_KOOTTAKSHARAM_TLLA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_TRA = MAL_VYANJANAKSHARAM_TA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_DDA = MAL_VYANJANAKSHARAM_DA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DA
MAL_KOOTTAKSHARAM_DDHA = MAL_VYANJANAKSHARAM_DA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DHA
MAL_KOOTTAKSHARAM_DRA = MAL_VYANJANAKSHARAM_DA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_NTA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_TA
MAL_KOOTTAKSHARAM_NNA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NA
MAL_KOOTTAKSHARAM_NTHA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_THA
MAL_KOOTTAKSHARAM_NMA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_MA
MAL_KOOTTAKSHARAM_NPA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_PA
MAL_KOOTTAKSHARAM_NDA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DA
MAL_KOOTTAKSHARAM_NDHA = MAL_VYANJANAKSHARAM_NA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_DHA

MAL_KOOTTAKSHARAM_PPA = MAL_VYANJANAKSHARAM_PA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_PA
MAL_KOOTTAKSHARAM_PRA = MAL_VYANJANAKSHARAM_PA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA
MAL_KOOTTAKSHARAM_PLLA = MAL_VYANJANAKSHARAM_PA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA

MAL_KOOTTAKSHARAM_BBA = MAL_VYANJANAKSHARAM_BA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_BA
MAL_KOOTTAKSHARAM_BRA = MAL_VYANJANAKSHARAM_BA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_BHRA = MAL_VYANJANAKSHARAM_BHA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_MMA = MAL_VYANJANAKSHARAM_MA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_MA
MAL_KOOTTAKSHARAM_MLLA = MAL_VYANJANAKSHARAM_MA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_MRA = MAL_VYANJANAKSHARAM_MA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA

MAL_KOOTTAKSHARAM_YYA = MAL_VYANJANAKSHARAM_YA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_YA

MAL_KOOTTAKSHARAM_LLA = MAL_VYANJANAKSHARAM_LA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LA

MAL_KOOTTAKSHARAM_VVA = MAL_VYANJANAKSHARAM_VA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_VA

MAL_KOOTTAKSHARAM_SHRA = MAL_VYANJANAKSHARAM_SHA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RA
MAL_KOOTTAKSHARAM_SHCA = MAL_VYANJANAKSHARAM_SHA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_CA
MAL_KOOTTAKSHARAM_SHCHA = MAL_VYANJANAKSHARAM_SHA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_CHA
MAL_KOOTTAKSHARAM_SHLLA = MAL_VYANJANAKSHARAM_SHA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_SHSHA = MAL_VYANJANAKSHARAM_SHA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_SHA

MAL_KOOTTAKSHARAM_SSA = MAL_VYANJANAKSHARAM_SA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_SA
MAL_KOOTTAKSHARAM_SLLA = MAL_VYANJANAKSHARAM_SA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_STHA = MAL_VYANJANAKSHARAM_SA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_THA

MAL_KOOTTAKSHARAM_SSTTA = MAL_VYANJANAKSHARAM_SSA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_TTA

MAL_KOOTTAKSHARAM_HLLA = MAL_VYANJANAKSHARAM_HA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA
MAL_KOOTTAKSHARAM_HMA = MAL_VYANJANAKSHARAM_HA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_MA
MAL_KOOTTAKSHARAM_HNA = MAL_VYANJANAKSHARAM_HA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_NA

MAL_KOOTTAKSHARAM_LLLLA = MAL_VYANJANAKSHARAM_LLA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_LLA

MAL_KOOTTAKSHARAM_RRRRA = MAL_VYANJANAKSHARAM_RRA + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RRA

MAL_KOOTTAKSHARAM_NRRA = MAL_CHILLAKSHARAM_N + MAL_VOWEL_VIRAMAM + MAL_VYANJANAKSHARAM_RRA

alphabets = [MAL_ANUSWARA_ABV, MAL_CHANDRABINDU, MAL_ANUSWARA, MAL_VISAGRA, MAL_SWARAKSHARAM_A, MAL_SWARAKSHARAM_AA, MAL_SWARAKSHARAM_I, MAL_SWARAKSHARAM_II, MAL_SWARAKSHARAM_U, MAL_SWARAKSHARAM_UU, MAL_SWARAKSHARAM_ERU, MAL_SWARAKSHARAM_E, MAL_SWARAKSHARAM_EE, MAL_SWARAKSHARAM_AI, MAL_SWARAKSHARAM_O, MAL_SWARAKSHARAM_OO, MAL_SWARAKSHARAM_OU, MAL_VYANJANAKSHARAM_KA, MAL_VYANJANAKSHARAM_KHA, MAL_VYANJANAKSHARAM_GA, MAL_VYANJANAKSHARAM_GHA, MAL_VYANJANAKSHARAM_NGA, MAL_VYANJANAKSHARAM_CA, MAL_VYANJANAKSHARAM_CHA, MAL_VYANJANAKSHARAM_JA, MAL_VYANJANAKSHARAM_JHA, MAL_VYANJANAKSHARAM_NJA, MAL_VYANJANAKSHARAM_TTA, MAL_VYANJANAKSHARAM_TTHA, MAL_VYANJANAKSHARAM_DDA, MAL_VYANJANAKSHARAM_DDHA, MAL_VYANJANAKSHARAM_NNA, MAL_VYANJANAKSHARAM_TA, MAL_VYANJANAKSHARAM_THA, MAL_VYANJANAKSHARAM_DA, MAL_VYANJANAKSHARAM_DHA, MAL_VYANJANAKSHARAM_NA, MAL_VYANJANAKSHARAM_PA, MAL_VYANJANAKSHARAM_PHA, MAL_VYANJANAKSHARAM_BA, MAL_VYANJANAKSHARAM_BHA, MAL_VYANJANAKSHARAM_MA, MAL_VYANJANAKSHARAM_YA, MAL_VYANJANAKSHARAM_RA, MAL_VYANJANAKSHARAM_RRA, MAL_VYANJANAKSHARAM_LA, MAL_VYANJANAKSHARAM_LLA, MAL_VYANJANAKSHARAM_ZHA, MAL_VYANJANAKSHARAM_VA, MAL_VYANJANAKSHARAM_SHA, MAL_VYANJANAKSHARAM_SSA, MAL_VYANJANAKSHARAM_SA, MAL_VYANJANAKSHARAM_HA, MAL_CHILLAKSHARAM_NN, MAL_CHILLAKSHARAM_N, MAL_CHILLAKSHARAM_RR, MAL_CHILLAKSHARAM_L, MAL_CHILLAKSHARAM_LL, MAL_VOWEL_AA, MAL_VOWEL_I, MAL_VOWEL_II, MAL_VOWEL_U, MAL_VOWEL_UU, MAL_VOWEL_R, MAL_VOWEL_E, MAL_VOWEL_EE, MAL_VOWEL_AI, MAL_VOWEL_O, MAL_VOWEL_OO, MAL_VOWEL_OU, MAL_VOWEL_VIRAMAM, MAL_VOWEL_DOT, MAL_HALF_CONSONANT_YA, MAL_HALF_CONSONANT_RA, MAL_HALF_CONSONANT_VA, MAL_KOOTTAKSHARAM_KKA, MAL_KOOTTAKSHARAM_KSSA, MAL_KOOTTAKSHARAM_KLLA, MAL_KOOTTAKSHARAM_KTA, MAL_KOOTTAKSHARAM_KRA, MAL_KOOTTAKSHARAM_GGA, MAL_KOOTTAKSHARAM_GLLA, MAL_KOOTTAKSHARAM_GRA, MAL_KOOTTAKSHARAM_GNA, MAL_KOOTTAKSHARAM_GDA, MAL_KOOTTAKSHARAM_GMA, MAL_KOOTTAKSHARAM_NGKA, MAL_KOOTTAKSHARAM_NGNGA, MAL_KOOTTAKSHARAM_CCA, MAL_KOOTTAKSHARAM_CCHA, MAL_KOOTTAKSHARAM_JJA, MAL_KOOTTAKSHARAM_JNJA, MAL_KOOTTAKSHARAM_NJNJA, MAL_KOOTTAKSHARAM_NJCA, MAL_KOOTTAKSHARAM_TTTTA, MAL_KOOTTAKSHARAM_TTRA, MAL_KOOTTAKSHARAM_DDDDA, MAL_KOOTTAKSHARAM_DDDDHA, MAL_KOOTTAKSHARAM_NNNNA, MAL_KOOTTAKSHARAM_NNTTA, MAL_KOOTTAKSHARAM_NNDDA, MAL_KOOTTAKSHARAM_NNDDHA, MAL_KOOTTAKSHARAM_NNMA, MAL_KOOTTAKSHARAM_TTA, MAL_KOOTTAKSHARAM_TTHA, MAL_KOOTTAKSHARAM_TNA, MAL_KOOTTAKSHARAM_TMA, MAL_KOOTTAKSHARAM_TBHA, MAL_KOOTTAKSHARAM_TSA, MAL_KOOTTAKSHARAM_TLLA, MAL_KOOTTAKSHARAM_TRA, MAL_KOOTTAKSHARAM_DDA, MAL_KOOTTAKSHARAM_DDHA, MAL_KOOTTAKSHARAM_DRA, MAL_KOOTTAKSHARAM_NTA, MAL_KOOTTAKSHARAM_NNA, MAL_KOOTTAKSHARAM_NTHA, MAL_KOOTTAKSHARAM_NMA, MAL_KOOTTAKSHARAM_NPA, MAL_KOOTTAKSHARAM_NDA, MAL_KOOTTAKSHARAM_NDHA, MAL_KOOTTAKSHARAM_PPA, MAL_KOOTTAKSHARAM_PRA, MAL_KOOTTAKSHARAM_PLLA, MAL_KOOTTAKSHARAM_BBA, MAL_KOOTTAKSHARAM_BRA, MAL_KOOTTAKSHARAM_BHRA, MAL_KOOTTAKSHARAM_MMA, MAL_KOOTTAKSHARAM_MLLA, MAL_KOOTTAKSHARAM_MRA, MAL_KOOTTAKSHARAM_YYA, MAL_KOOTTAKSHARAM_LLA, MAL_KOOTTAKSHARAM_VVA, MAL_KOOTTAKSHARAM_SHRA, MAL_KOOTTAKSHARAM_SHCA, MAL_KOOTTAKSHARAM_SHCHA, MAL_KOOTTAKSHARAM_SHLLA, MAL_KOOTTAKSHARAM_SHSHA, MAL_KOOTTAKSHARAM_SSA, MAL_KOOTTAKSHARAM_SLLA, MAL_KOOTTAKSHARAM_STHA, MAL_KOOTTAKSHARAM_SSTTA, MAL_KOOTTAKSHARAM_HLLA, MAL_KOOTTAKSHARAM_HMA, MAL_KOOTTAKSHARAM_HNA, MAL_KOOTTAKSHARAM_LLLLA, MAL_KOOTTAKSHARAM_RRRRA, MAL_KOOTTAKSHARAM_NRRA]
